default_platform(:android)

platform :android do
  desc "Build debug APK"
  lane :debug do
    gradle(
      task: "assembleDebug",
      project_dir: "android/"
    )
  end

  desc "Build release APK"
  lane :release do
    gradle(
      task: "assembleRelease",
      project_dir: "android/"
    )
  end

  desc "Build AAB for Play Store"
  lane :bundle do
    gradle(
      task: "bundleRelease",
      project_dir: "android/"
    )
  end

  desc "Deploy to Google Play Store (internal track)"
  lane :deploy_internal do
    gradle(
      task: "bundleRelease",
      project_dir: "android/"
    )
    upload_to_play_store(
      track: "internal",
      aab: "android/app/build/outputs/bundle/release/app-release.aab"
    )
  end
end
